### ISSUE TITLE
Determining which player is selecting a space

### ISSUE THREAD

**Issue by kristynrb** [kristynrb/tic_tac_toe#1]
Hi! I've been trying to determine which player is selecting a space in my tic tac toe game. 

I've done the following:

Randomly generated who would go first. I then tried to set it up to assign an empty space to the contents of the player, but couldn't figure out how to alternate players.

Here's my text... but I was evaluating whether to use .text or .val:
I was looking at this site: http://api.jquery.com/val/

``` JavaScript
playMode: function () {
    // the player that is chosen at random (var randomPlayer will have a value of either "O" or "X" 
    // will have control of the first click 
    var firstPlayer = randomPlayer
        if firstPlyer = "X"{
            var secondPlayer = "O";
        } else {
            var secondPlayer = "X";
        };

        $('td').on('click', function () {
            if ($('td').text() = null) {
                $('td').push(firstPlayer);
};
```

I then realized that it may be easier if I set a toggle on the click to alternate which text would go in the element. Here's what I did to test it out:

``` JavaScript
$( "#space" ).toggle(function() {
    alert( "First player move." );
        }, function() {
        alert( "Second player move." );
    })
}
```

This is not working the way that I would like.

I found information about this from: https://api.jquery.com/toggle-event/

This might be something best discussed in person at my meeting tomorrow. Thanks!

**Comment by short-matthew-f** [comment]
Added player array, currentPlayer & nextPlayer functions...
