### ISSUE TITLE
Issue with changing the text in an element

### ISSUE THREAD

**Issue by kristynrb** [kristynrb/tic_tac_toe#2]
I've been trying to update the text in an html element. I've been able to successfully grab the element when I click on the box, but I'm failing to update the text.

I've tried:
.text
http://api.jquery.com/text/
.append
http://api.jquery.com/append/
.html
http://api.jquery.com/html/

Here's my code so far:

``` JavaScript

var secondPlayer = {
    name: "",
    piece: "O",
    score: 0
};

assignSpace: function() {       
    $('td').on('click', function() {
        alert("you clicked a space");   // for testing purposes
        console.log(this);
//      var that = this;
//      var that = that.text(secondPlayer.piece);
    });
},
```

I just started messing with the "that = this"...

When I console.log(this), I am given the exact element that I'd like to change - now I just  need to add the text.

Thanks for your help!

**Comment by short-matthew-f** [comment]
used jQuery .text() on an jQuery element to write the currentPlayer().piece.
